// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Test struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
}
