// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	Test(ctx context.Context, id int32) (Test, error)
}

var _ Querier = (*Queries)(nil)
