// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test.sql

package database

import (
	"context"
)

const test = `-- name: Test :one
SELECT id, name, created_at FROM test WHERE id = $1
`

func (q *Queries) Test(ctx context.Context, id int32) (Test, error) {
	row := q.db.QueryRowContext(ctx, test, id)
	var i Test
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
